name: Release
description: Run Release Please for automated versioning

inputs:
  token:
    description: GitHub token for creating releases and PRs
    required: true
  config-file:
    description: Path to release-please config file
    default: '.release-please-config.json'
  manifest-file:
    description: Path to release-please manifest file
    default: '.release-please-manifest.json'

outputs:
  releases_created:
    description: Whether any releases were created
    value: ${{ steps.release.outputs.releases_created }}
  paths_released:
    description: JSON array of paths that were released
    value: ${{ steps.release.outputs.paths_released }}

runs:
  using: composite
  steps:
    - name: Release Please
      id: release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        config-file: ${{ inputs.config-file }}
        manifest-file: ${{ inputs.manifest-file }}
