name: Publish to npm
description: Publish packages to npm or GitHub Packages registry

inputs:
  node-version-file:
    description: Path to .nvmrc or similar file
    default: '.nvmrc'
  registry-url:
    description: npm registry URL (without https://)
    default: 'npm.pkg.github.com'
  scope:
    description: npm scope (e.g., @astrale-os)
    required: true
  access:
    description: Package access level (public or restricted)
    default: 'restricted'
  token:
    description: npm registry token
    required: true
  frozen-lockfile:
    description: Use frozen lockfile (set to false if lockfile may not exist)
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js (with cache)
      if: inputs.frozen-lockfile == 'true'
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm
        registry-url: https://${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}

    - name: Setup Node.js (no cache)
      if: inputs.frozen-lockfile != 'true'
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        registry-url: https://${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}

    - name: Install dependencies (frozen)
      if: inputs.frozen-lockfile == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Install dependencies (no frozen)
      if: inputs.frozen-lockfile != 'true'
      shell: bash
      run: pnpm install
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Build packages
      shell: bash
      run: pnpm build
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}

    - name: Publish packages
      shell: bash
      run: |
        output=$(pnpm -r publish --access ${{ inputs.access }} --no-git-checks 2>&1) || exit_code=$?
        echo "$output"
        if [ -n "$exit_code" ]; then
          if echo "$output" | grep -q "npm error" && ! echo "$output" | grep "npm error" | grep -q "already published"; then
            echo "::error::Publish failed with errors"
            exit 1
          fi
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
